#!/usr/bin/env bash
# configure.sh — interactive setup for the worktrees tooling.
#
# Prompts for the two home directories, writes a fish config override that
# loads before worktrees.fish, and seeds WORKTREE-GROUPS with a commented
# example. Safe to re-run (idempotent, prompts re-ask on each run).
#
# Usage:   ./configure.sh
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# -- arg parsing ------------------------------------------------------------------
# `--defaults` runs non-interactively with the default homes (no prompts) and is
# used by install.sh for one-shot zero-state provisioning. `--help` prints usage.

DEFAULTS=0
case "${1:-}" in
    --defaults) DEFAULTS=1 ;;
    --help|-h)
        echo "usage: ./configure.sh [--defaults]"
        echo "  --defaults  run non-interactively with default homes (no prompts)"
        exit 0 ;;
    *)
        if [[ $# -gt 0 ]]; then
            echo "configure.sh: unknown argument: $1" >&2
            echo "usage: ./configure.sh [--defaults]" >&2
            exit 1
        fi
        ;;
esac

# -- 0. environment fast-fail ------------------------------------------------------
# Refuse to configure on unsupported fish/git so failures are clear and
# immediate, not a cryptic first-use error later.
# NOTE: `require_version` is duplicated in install.sh — keep the two in sync.

require_version() {
    # $1 = tool name, $2 = current version (X.Y[.Z]), $3 = required (X.Y[.Z]).
    # Compares major/minor/patch (defaulted to 0) — mirrors worktrees.fish's
    # __wt_version_ge.
    local name="$1" cur="$2" req="$3"
    IFS=. read -r -a c <<<"$cur"; IFS=. read -r -a r <<<"$req"
    while (( ${#c[@]} < 3 )); do c+=(0); done
    while (( ${#r[@]} < 3 )); do r+=(0); done
    if (( c[0]*1000000 + c[1]*1000 + c[2] >= r[0]*1000000 + r[1]*1000 + r[2] )); then
        return 0
    fi
    echo "configure.sh: $name $cur is too old (need >= $req). upgrade and re-run." >&2
    return 1
}

if ! command -v fish >/dev/null 2>&1; then
    echo "configure.sh: fish is not installed (required for worktrees.fish). install fish first." >&2
    exit 1
fi
if ! command -v git >/dev/null 2>&1; then
    echo "configure.sh: git is not installed (required). install git first." >&2
    exit 1
fi

FISH_VER="$(fish --version 2>/dev/null | sed -n 's/.*version \([0-9][0-9.]*\).*/\1/p')"
GIT_VER="$(git --version 2>/dev/null | sed -n 's/.*version \([0-9][0-9.]*\).*/\1/p')"
test -n "$FISH_VER" || { echo "configure.sh: could not determine fish version" >&2; exit 1; }
test -n "$GIT_VER"  || { echo "configure.sh: could not determine git version" >&2; exit 1; }

require_version fish "$FISH_VER" 3.3 || exit 1
require_version git  "$GIT_VER"  2.31 || exit 1
echo "environment ok: fish $FISH_VER, git $GIT_VER"

# -- collect values with defaults -------------------------------------------------

if [[ "$DEFAULTS" -eq 1 ]]; then
    __wt_github_home="$HOME/github"
    __wt_worktree_home="$HOME/git-worktrees"
else
    read -rp "GitHub home (where main clones live) [$HOME/github]: " answer
    __wt_github_home="${answer:-$HOME/github}"

    read -rp "Worktree home (where worktrees live) [$HOME/git-worktrees]: " answer
    __wt_worktree_home="${answer:-$HOME/git-worktrees}"
fi

# -- write the fish config override ------------------------------------------------

CONF_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/fish/conf.d"
CONF_FILE="$CONF_DIR/worktrees-config.fish"
mkdir -p "$CONF_DIR"

cat > "$CONF_FILE" <<EOF
# generated by git-worktrees configure — edit here, not in worktrees.fish
set -g __wt_github_home "$__wt_github_home"
set -g __wt_worktree_home "$__wt_worktree_home"
EOF

echo "wrote $CONF_FILE"

# -- seed WORKTREE-GROUPS if absent ------------------------------------------------

GROUPS_FILE="$__wt_worktree_home/WORKTREE-GROUPS"
if [[ ! -f "$GROUPS_FILE" ]]; then
    mkdir -p "$__wt_worktree_home"
    cat > "$GROUPS_FILE" <<'EOF'
# WORKTREE-GROUPS — named repo groups for the worktree tooling.
# Format: one group per line, `name: repo1 repo2` (repos alphabetized).
# `-g NAME` uses a group; `--save NAME` (with --repos) creates/refreshes one.
#
# Example (uncomment and edit):
# default: grantha-data grantha-explorer
EOF
    echo "seeded $GROUPS_FILE (edit it to add your groups)"
else
    echo "$GROUPS_FILE already exists — leaving it untouched"
fi

echo
echo "Next step: run ./install.sh (symlinks worktrees.fish + sets the git plan alias + installs the opencode model-routing alarm)."
